name: Auto Blog Generator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Script to Generate Article
        env:
          GEMINI_API_KEY: "AIzaSyB0bTzkFYf0g6FnmMURLEgob8khEwginak"
        run: python generate_blog.py

      - name: Commit and Push New Article
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated unique daily blog post by AI"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/zaiddehwar993-netizen/codewithzaid.git main
          
